### ISSUE TITLE
Prettier & suggestion performance issue

### ISSUE THREAD

**Issue by castrix** [sapphi-red/vite-boilerplate-plus#2]
Hi! I'm using your boilerplate for my project, but I'm having performance issue with this boilerplate, when I try to wait for `quick fixes` or type suggestion from vscode, it's loading pretty slow.

**Comment by sapphi-red** [comment]
I need more info to investigate (etc VSCode extensions you use).
I have updated package versions so it may solve that.

**Comment by sapphi-red** [comment]
Closing due to lack of response.
